name: Generuj dokumentáciu

permissions:
  contents: write

on:
  push:
    branches: [main]
    paths:
      - "src/**/*.sv"
      - ".github/workflows/gen-docs.yml"
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Nastav Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Inštaluj závislosti
        run: |
          pip install --upgrade pip
          pip install markdown

      - name: Generuj Markdown dokumentáciu
        run: |
          python scripts/extract_sv_docs.py
          python scripts/generate_index.py

      - name: Konvertuj Markdown -> HTML
        run: python scripts/md_to_html.py

      - name: Deploy do gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      
          git checkout --orphan gh-pages
          git rm -rf .
      
          # zachovaj adresárovú štruktúru modules/ + README.html
          #cp -r docs_md/* .
          mv docs_md/* .
      
          # zabráni spracovaniu Jekyll
          touch .nojekyll
      
          git add .
          git commit -m "📝 Auto-generovaná dokumentácia a HTML"
          git push --force origin gh-pages
